# Site
repository: AqsaSharif/aqsasharif.github.io
#favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name:  Aqsa Sharif
title: Student
email: aqsasharif19@gmail.com
#Resume: [here](AqsaSharif_Resume.pdf).
website: https://aqsasharif.github.io

darkmode: false

# Social links
twitter_username: AqsaSharif19
# github_username:  AqsaSharif
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: physio.health20
linkedin_username: aqsasharif
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: UCoBDc8d6FEZfT--65_IhipQ
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: Google Scholar
#  icon: fa-google
#  url: https://scholar.google.com/citations?user=Lg7o8R8AAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an Physio Therapist student and researcher in [NCS University System](http://ncs.edu.pk/). My area of research includes
    - Musculoskeletal
    - Neuro-Physiotherapy 
    

  Here is the [link](AqsaSharif_Resume.pdf) to my resume.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Key Achievements & Duties  #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    - **1x Deans List and 2x Rector List Certifications** - NCS University System, Pakistan - August 2016-June 2021
    - **Winner of Speech Competition** -Islamia College, Pakistan - August 2014
    - **4x50 Meter Relay Race** - Saint Francis High School, Pakistan - August 2014

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
